# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multybook.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(311, 215)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 311, 211))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.add_author = QtWidgets.QLineEdit(self.centralwidget)
        self.add_author.setGeometry(QtCore.QRect(140, 10, 161, 21))
        self.add_author.setObjectName("add_author")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.box_add_author = QtWidgets.QComboBox(self.centralwidget)
        self.box_add_author.setGeometry(QtCore.QRect(140, 50, 161, 21))
        self.box_add_author.setObjectName("box_add_author")
        self.add_new_author = QtWidgets.QLineEdit(self.centralwidget)
        self.add_new_author.setEnabled(False)
        self.add_new_author.setGeometry(QtCore.QRect(140, 90, 161, 21))
        self.add_new_author.setObjectName("add_new_author")
        self.btn_add_ab = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_ab.setGeometry(QtCore.QRect(10, 130, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_add_ab.setFont(font)
        self.btn_add_ab.setObjectName("btn_add_ab")
        self.chekbox_author = QtWidgets.QCheckBox(self.centralwidget)
        self.chekbox_author.setGeometry(QtCore.QRect(10, 90, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chekbox_author.setFont(font)
        self.chekbox_author.setObjectName("chekbox_author")
        self.label_warning = QtWidgets.QLabel(self.centralwidget)
        self.label_warning.setGeometry(QtCore.QRect(10, 169, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_warning.setFont(font)
        self.label_warning.setText("")
        self.label_warning.setObjectName("label_warning")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 22))
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Имя книги"))
        self.label_2.setText(_translate("MainWindow", "Автор"))
        self.btn_add_ab.setText(_translate("MainWindow", "Добавить"))
        self.chekbox_author.setText(_translate("MainWindow", "Новый автор"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
