from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BaseWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("...")
        MainWindow.resize(801, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 70, 801, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_catalog = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_catalog.setEnabled(True)
        self.btn_catalog.setObjectName("btn_catalog")
        self.verticalLayout.addWidget(self.btn_catalog)
        self.btn_readers = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_readers.setObjectName("btn_readers")
        self.verticalLayout.addWidget(self.btn_readers)
        self.btn_add_readers = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_add_readers.setObjectName("btn_add_readers")
        self.verticalLayout.addWidget(self.btn_add_readers)
        self.btn_add_book = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_add_book.setObjectName("btn_add_book")
        self.verticalLayout.addWidget(self.btn_add_book)
        self.btn_rental_books = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_rental_books.setObjectName("btn_rental_books")
        self.verticalLayout.addWidget(self.btn_rental_books)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 470, 801, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_del_book_for_reader = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_del_book_for_reader.setObjectName("btn_del_book_for_reader")
        self.horizontalLayout.addWidget(self.btn_del_book_for_reader)
        self.btn_del_book = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_del_book.setObjectName("btn_del_book")
        self.horizontalLayout.addWidget(self.btn_del_book)
        self.label_mini_library = QtWidgets.QLabel(self.centralwidget)
        self.label_mini_library.setGeometry(QtCore.QRect(1, 6, 801, 51))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.label_mini_library.setFont(font)
        self.label_mini_library.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mini_library.setObjectName("label_mini_library")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_catalog.setText(_translate("MainWindow", "Каталог книг"))
        self.btn_readers.setText(_translate("MainWindow", "Посмотреть читателей"))
        self.btn_add_readers.setText(_translate("MainWindow", "Добавить читателей"))
        self.btn_add_book.setText(_translate("MainWindow", "Добавить книгу или автора"))
        self.btn_rental_books.setText(_translate("MainWindow", "Продлить/добавить в прокат книгу"))
        self.btn_del_book_for_reader.setText(_translate("MainWindow", "Удалить у читателя книгу с проката"))
        self.btn_del_book.setText(_translate("MainWindow", "Удалить книгу"))
        self.label_mini_library.setText(_translate("MainWindow", "Управление мини библиотекой"))

