# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catalog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CatalogList(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainVerticalLayout.setContentsMargins(20, 20, 20, 20)
        self.mainVerticalLayout.setSpacing(15)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.mainVerticalLayout.addWidget(self.title_label)
        self.searchHorizontalLayout = QtWidgets.QHBoxLayout()
        self.searchHorizontalLayout.setSpacing(15)
        self.searchHorizontalLayout.setObjectName("searchHorizontalLayout")
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        self.search.setMinimumHeight(40)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.search.setFont(font)
        self.search.setObjectName("search")
        self.searchHorizontalLayout.addWidget(self.search)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setMinimumHeight(40)
        self.btn_search.setMinimumWidth(120)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn_search.setFont(font)
        self.btn_search.setObjectName("btn_search")
        self.searchHorizontalLayout.addWidget(self.btn_search)
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setMinimumHeight(40)
        self.btn_clear.setMinimumWidth(100)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.searchHorizontalLayout.addWidget(self.btn_clear)
        self.mainVerticalLayout.addLayout(self.searchHorizontalLayout)
        self.catalog_table = QtWidgets.QTableWidget(self.centralwidget)
        self.catalog_table.setMinimumHeight(400)
        self.catalog_table.setMinimumWidth(900)
        self.catalog_table.setAlternatingRowColors(True)
        self.catalog_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.catalog_table.setCornerButtonEnabled(False)
        self.catalog_table.setObjectName("catalog_table")
        self.catalog_table.setColumnCount(0)
        self.catalog_table.setRowCount(0)
        self.mainVerticalLayout.addWidget(self.catalog_table)
        self.bottomButtonsLayout = QtWidgets.QHBoxLayout()
        self.bottomButtonsLayout.setSpacing(15)
        self.bottomButtonsLayout.setObjectName("bottomButtonsLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomButtonsLayout.addItem(spacerItem)
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refresh.setMinimumHeight(45)
        self.btn_refresh.setMinimumWidth(140)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn_refresh.setFont(font)
        self.btn_refresh.setObjectName("btn_refresh")
        self.bottomButtonsLayout.addWidget(self.btn_refresh)
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setMinimumHeight(45)
        self.btn_back.setMinimumWidth(140)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.bottomButtonsLayout.addWidget(self.btn_back)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomButtonsLayout.addItem(spacerItem1)
        self.mainVerticalLayout.addLayout(self.bottomButtonsLayout)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 992, 20))
        self.menubar.setObjectName("menubar")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Каталог библиотеки"))
        MainWindow.setStyleSheet(_translate("MainWindow", "QWidget {\n"
"    background-color: #f5f5f5;\n"
"   }\n"
"   QTableWidget {\n"
"    background-color: white;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 10px;\n"
"    gridline-color: #e0e0e0;\n"
"    font-size: 12px;\n"
"   }\n"
"   QTableWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"   }\n"
"   QTableWidget::item:selected {\n"
"    background-color: #e3f2fd;\n"
"    color: #1976d2;\n"
"   }\n"
"   QHeaderView::section {\n"
"    background-color: #2196f3;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"   }"))
        self.title_label.setText(_translate("MainWindow", "📚 Каталог библиотеки"))
        self.title_label.setStyleSheet(_translate("MainWindow", "color: #2d3e50; background: #eaf6fb; border-radius: 10px; padding: 15px; margin-bottom: 10px;"))
        self.search.setPlaceholderText(_translate("MainWindow", "🔍 Введите название книги, автора или жанр для поиска..."))
        self.search.setStyleSheet(_translate("MainWindow", "QLineEdit {\n"
"          background-color: white;\n"
"          border: 2px solid #e0e0e0;\n"
"          border-radius: 20px;\n"
"          padding: 8px 15px;\n"
"          font-size: 14px;\n"
"         }\n"
"         QLineEdit:focus {\n"
"          border-color: #2196f3;\n"
"          background-color: #fafafa;\n"
"         }"))
        self.btn_search.setText(_translate("MainWindow", "🔍 Искать"))
        self.btn_search.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"          background-color: #2196f3;\n"
"          color: white;\n"
"          border: none;\n"
"          border-radius: 20px;\n"
"          padding: 10px 20px;\n"
"          font-size: 14px;\n"
"          font-weight: bold;\n"
"         }\n"
"         QPushButton:hover {\n"
"          background-color: #1976d2;\n"
"         }\n"
"         QPushButton:pressed {\n"
"          background-color: #1565c0;\n"
"         }"))
        self.btn_clear.setText(_translate("MainWindow", "❌ Сброс"))
        self.btn_clear.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"          background-color: #ff5722;\n"
"          color: white;\n"
"          border: none;\n"
"          border-radius: 20px;\n"
"          padding: 10px 15px;\n"
"          font-size: 14px;\n"
"          font-weight: bold;\n"
"         }\n"
"         QPushButton:hover {\n"
"          background-color: #e64a19;\n"
"         }\n"
"         QPushButton:pressed {\n"
"          background-color: #d84315;\n"
"         }"))
        self.catalog_table.setSortingEnabled(True)
        self.btn_refresh.setText(_translate("MainWindow", "🔄 Обновить"))
        self.btn_refresh.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"          background-color: #4caf50;\n"
"          color: white;\n"
"          border: none;\n"
"          border-radius: 22px;\n"
"          padding: 12px 20px;\n"
"          font-size: 14px;\n"
"          font-weight: bold;\n"
"         }\n"
"         QPushButton:hover {\n"
"          background-color: #45a049;\n"
"         }\n"
"         QPushButton:pressed {\n"
"          background-color: #3d8b40;\n"
"         }"))
        self.btn_back.setText(_translate("MainWindow", "⬅️ Назад"))
        self.btn_back.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"          background-color: #9e9e9e;\n"
"          color: white;\n"
"          border: none;\n"
"          border-radius: 22px;\n"
"          padding: 12px 20px;\n"
"          font-size: 14px;\n"
"          font-weight: bold;\n"
"         }\n"
"         QPushButton:hover {\n"
"          background-color: #757575;\n"
"         }\n"
"         QPushButton:pressed {\n"
"          background-color: #616161;\n"
"         }"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
