from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddBooks(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("")
        MainWindow.resize(311, 215)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name_book = QtWidgets.QLabel(self.centralwidget)
        self.label_name_book.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name_book.setFont(font)
        self.label_name_book.setObjectName("label")
        self.add_name_book = QtWidgets.QLineEdit(self.centralwidget)
        self.add_name_book.setGeometry(QtCore.QRect(140, 10, 161, 21))
        self.add_name_book.setObjectName("add_author")
        self.label_add_author = QtWidgets.QLabel(self.centralwidget)
        self.label_add_author.setGeometry(QtCore.QRect(10, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_add_author.setFont(font)
        self.label_add_author.setObjectName("label_2")
        self.box_add_author = QtWidgets.QComboBox(self.centralwidget)
        self.box_add_author.setGeometry(QtCore.QRect(140, 50, 161, 21))
        self.box_add_author.setObjectName("box_add_author")
        self.line_add_new_author = QtWidgets.QLineEdit(self.centralwidget)
        self.line_add_new_author.setEnabled(False)
        self.line_add_new_author.setGeometry(QtCore.QRect(140, 90, 161, 21))
        self.line_add_new_author.setObjectName("add_new_author")
        self.btn_add_ab = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_ab.setGeometry(QtCore.QRect(10, 130, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_add_ab.setFont(font)
        self.btn_add_ab.setObjectName("btn_add_ab")
        self.chekbox_author = QtWidgets.QCheckBox(self.centralwidget)
        self.chekbox_author.setGeometry(QtCore.QRect(10, 90, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chekbox_author.setFont(font)
        self.chekbox_author.setObjectName("chekbox_author")
        self.label_warning = QtWidgets.QLabel(self.centralwidget)
        self.label_warning.setGeometry(QtCore.QRect(10, 169, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_warning.setFont(font)
        self.label_warning.setText("")
        self.label_warning.setObjectName("label_warning")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name_book.setText(_translate("MainWindow", "Имя книги"))
        self.label_add_author.setText(_translate("MainWindow", "Автор"))
        self.btn_add_ab.setText(_translate("MainWindow", "Добавить"))
        self.chekbox_author.setText(_translate("MainWindow", "Новый автор"))

