# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multyreader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddReaders(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("")
        MainWindow.resize(294, 143)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name_reader = QtWidgets.QLabel(self.centralwidget)
        self.label_name_reader.setGeometry(QtCore.QRect(10, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name_reader.setFont(font)
        self.label_name_reader.setObjectName("label")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(10, 90, 250, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_error.setFont(font)
        self.name_reader = QtWidgets.QLineEdit(self.centralwidget)
        self.name_reader.setGeometry(QtCore.QRect(140, 10, 141, 21))
        self.name_reader.setObjectName("name_reader")
        self.btn_add_reader = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_reader.setGeometry(QtCore.QRect(10, 50, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_add_reader.setFont(font)
        self.btn_add_reader.setObjectName("btn_add_reader")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name_reader.setText(_translate("MainWindow", "Имя читателя"))
        self.btn_add_reader.setText(_translate("MainWindow", "Добавить"))

