# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renta_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RentaAddBooks(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("")
        MainWindow.resize(375, 147)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name_reader_rental = QtWidgets.QLabel(self.centralwidget)
        self.label_name_reader_rental.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name_reader_rental.setFont(font)
        self.label_name_reader_rental.setObjectName("label_name_reader_rental")
        self.box_readers_rental = QtWidgets.QComboBox(self.centralwidget)
        self.box_readers_rental.setGeometry(QtCore.QRect(190, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_readers_rental.setFont(font)
        self.box_readers_rental.setObjectName("box_readers_rental")
        self.btn_rental_book = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rental_book.setGeometry(QtCore.QRect(10, 70, 361, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_rental_book.setFont(font)
        self.btn_rental_book.setObjectName("btn_rental_book")
        self.box_books_rental = QtWidgets.QComboBox(self.centralwidget)
        self.box_books_rental.setGeometry(QtCore.QRect(190, 40, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_books_rental.setFont(font)
        self.box_books_rental.setObjectName("box_books_rental")
        self.label_name_book_rental = QtWidgets.QLabel(self.centralwidget)
        self.label_name_book_rental.setGeometry(QtCore.QRect(10, 40, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name_book_rental.setFont(font)
        self.label_name_book_rental.setObjectName("label_2")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name_reader_rental.setText(_translate("MainWindow", "Имя читателя"))
        self.btn_rental_book.setText(_translate("MainWindow", "Продлить/добавить в прокат на 30 дней"))
        self.label_name_book_rental.setText(_translate("MainWindow", "Название книги"))

